// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PruebaProgramadorBackendCSharp.Data;

#nullable disable

namespace PruebaProgramadorBackendCSharp.Migrations
{
    [DbContext(typeof(PruebaDbContext))]
    partial class PruebaDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PruebaProgramadorBackendCSharp.Models.MarcaAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("MarcasAutos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Descripcion = "Marca japonesa",
                            FechaCreacion = new DateTime(1937, 8, 28, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Toyota"
                        },
                        new
                        {
                            Id = 2,
                            Descripcion = "Marca estadounidense",
                            FechaCreacion = new DateTime(1903, 6, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "Ford"
                        },
                        new
                        {
                            Id = 3,
                            Descripcion = "Marca alemana",
                            FechaCreacion = new DateTime(1916, 3, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            Nombre = "BMW"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
